# Generated by Django 3.1.3 on 2020-12-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201204_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wintotals',
            options={'ordering': ['-winnings']},
        ),
        migrations.AddField(
            model_name='points',
            name='overall_rank',
            field=models.IntegerField(default=0),
        ),
    ]
